# SOPS configuration for secret encryption
creation_rules:
  - path_regex: '.*secret\.enc\.yaml$'
    encrypted_regex: ^(data|stringData)$
    age: age1j5j4x77dv7efrwssv9tvaltqyxstdywer77qtd2c546e8h0zpccsqjk89x

