# This file is encrypted with SOPS
# To encrypt: sops -e -i workloads/wordpress/secret.enc.yaml
# WordPress database credentials (must match MySQL secret values)
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
  namespace: wordpress
type: Opaque
stringData:
  username: wordpress
  password: wordpress123

